paths:
    required: true
    type: list
    minlength: 1
    schema:
        type: string

collection:
    required: false
    type: dict
    allow_unknown: true
    schema:
        id:
            required: false
            type: dict
        licence:
            required: false
            type: string
        description:
            required: false
            type: string
        extraction_methods:
            required: false
            type: list
            allow_unknown: true
item:
    required: false
    type: dict
    allow_unknown: true
    schema:
        id:
            required: false
            type: dict
        extraction_methods:
            required: false
            type: list
            allow_unknown: true

asset:
    required: false
    type: dict
    allow_unknown: true
    schema:
        id:
            required: false
            type: dict
        extraction_methods:
            required: false
            type: list
            allow_unknown: true

templates:
    required: false
    allow_unknown: false
    type: dict
    schema:
        title_template:
            required: false
            type: string
        description_template:
            required: false
            type: string
